### ISSUE TITLE
Typo in `ManeuverParameters.msg` field

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-msgs#122]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The negotiation type field for the `ManeuverPlanning.msg` message has a typo. It should be `negotiation_type`, not `neogition_type`.

### Carma version where this issue was discovered

Problem discovered in `develop`, but it also affects `noetic/develop`. Problem appears to be present for the file's entire history in Git.

### Expected behavior
The negotiation type field for the `ManeuverPlanning.msg` message should be `negotiation_type`.

### Actual behavior

The negotiation type field for the `ManeuverPlanning.msg` message is `neogition_type`.

### Steps to reproduce the actual behavior

Issue evident upon inspection.

### Related work

usdot-fhwa-stol/carma-platform#1371
#126

**Comment by msmcconnell** [comment]
This has been resolved on develop, but will need to be ported to noetic/develop when possible
