### ISSUE TITLE
Add support for CARMA cooperative perception

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-msgs#215]
### Summary

We are implementing a cooperative perception stack in CARMA, so we need some custom message types to facilitate inter-node communication.

### Reasoning for new functionality

See above

**Comment by MishkaMN** [comment]
https://github.com/usdot-fhwa-stol/carma-msgs/issues/222
https://github.com/usdot-fhwa-stol/carma-msgs/issues/224
